### ISSUE TITLE
States as morphisms (𝟙 → S) probably not needed here

### ISSUE THREAD

**Issue by andreasabel** [ayberkt/agda-brzozowski#5]
https://github.com/ayberkt/agda-brzozowski/blob/772faa8cf431dd33786e9a2f1dd32df1296d2cd9/CoalgebraicAutomata.agda#L61

While the paper works in a categorical setting where elements are represented by morphisms out of the terminal object, in Agda you are welcome just to use elements of sets.
`(𝟙 → S)` should be replaceable by just `S` everywhere.

**Comment by ayberkt** [comment]
I was initially using just `S` but then I realized that in the "initial becomes final" part of the construction, they use the contravariant powerset functor on `𝟙 → X` to get `𝟚^X → 𝟚` which is exactly the output function in the powerset automaton. I wanted to follow their uniform presentation which is why i used `𝟙 → X` instead of `X`.

**Comment by ayberkt** [comment]
Actually, it was a much better idea to make `S` into `𝟙 → S` when I needed to apply the contravariant powerset functor instead of using `𝟙 → S` everywhere. Fixed in 868f263!
